export const GENERATE_INITIAL_MAP = "GENERATE_INITIAL_MAP";
export const GENERATE_RAMDOM_MAP = "GENERATE_RAMDOM_MAP";
export const GENERATE_MAPCHIP_SRCS = "GENERATE_MAPCHIP_SRCS";
export const CHANGE_ONCE_MAPCHIP_FROM_XY = "CHANGE_ONCE_MAPCHIP_FROM_XY";

const Actions = {
  GENERATE_INITIAL_MAP,
  GENERATE_RAMDOM_MAP,
  GENERATE_MAPCHIP_SRCS,
  CHANGE_ONCE_MAPCHIP_FROM_XY
};
export default Actions;
