export const PLAYER_MOVE_LEFT = "PLAYER_MOVE_LEFT";
export const PLAYER_MOVE_RIGHT = "PLAYER_MOVE_RIGHT";
export const PLAYER_MOVE_TOP = "PLAYER_MOVE_TOP";
export const PLAYER_MOVE_BOTTOM = "PLAYER_MOVE_BOTTOM";
